workspace:
  base: /var/www/owncloud
  path: server/apps/activity

pipeline:
  install-core:
    image: owncloudci/core
    version: ${OC_VERSION}
    pull: true
    core_path: /var/www/owncloud/server
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    when:
      matrix:
        NEED_CORE: true

  install-testrunner:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone -b master --depth=1 https://github.com/owncloud/core.git /var/www/owncloud/server/testrunner
      - cp -r /var/www/owncloud/server/apps/activity /var/www/owncloud/server/testrunner/apps/
      - cd /var/www/owncloud/server/testrunner
      - make install-composer-deps
      - make vendor-bin-deps
    when:
      matrix:
        USE_RELEASE_TARBALL: true

  install-fed-server:
    image: owncloudci/core
    pull: true
    version: ${FEDERATION_OC_VERSION}
    core_path: /var/www/owncloud/fed-server
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  configure-federation-server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - echo "export TEST_SERVER_FED_URL=http://federated" > /var/www/owncloud/saved-settings.sh
      - cd /var/www/owncloud/fed-server
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=federated
      - php occ log:manage --level 0
      - php occ config:list
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/server
      - php occ a:l
      - php occ a:e activity
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ log:manage --level 0
    when:
      matrix:
        NEED_INSTALL_APP: true

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /var/www/owncloud -R
      - if [ "${USE_RELEASE_TARBALL}" = "true" ];
        then
        chmod 777 /var/www/owncloud/server/testrunner/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/server/testrunner/tests/acceptance/run.sh;
        else
        chmod 777 /var/www/owncloud/server/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/server/tests/acceptance/run.sh;
        fi
    when:
      matrix:
        NEED_SERVER: true

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - COVERAGE=${COVERAGE}
    commands:
      - if [ -z "${COVERAGE}" ]; then make test-php-unit; fi
      - if [ "${COVERAGE}" = "true" ]; then make test-php-unit-dbg; fi
    when:
      matrix:
        TEST_SUITE: phpunit

  js-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-js
    when:
      matrix:
        TEST_SUITE: javascript

  api-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - TEST_SERVER_URL=http://server
      - BEHAT_SUITE=${BEHAT_SUITE}
    commands:
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/server/testrunner/apps/activity; fi
      - make test-acceptance-api
    when:
      matrix:
        TEST_SUITE: api-acceptance

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://server
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
    commands:
      - touch /var/www/owncloud/saved-settings.sh
      - . /var/www/owncloud/saved-settings.sh
      - if [ "${USE_RELEASE_TARBALL}" = "true" ]; then cd /var/www/owncloud/server/testrunner/apps/activity; fi
      - make test-acceptance-webui
    when:
      matrix:
        TEST_SUITE: web-acceptance

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
      - tests/output/clover.xml
    when:
      matrix:
        COVERAGE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=autotest
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
       - ORACLE_USER=system
       - ORACLE_PASSWORD=oracle
       - ORACLE_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: oci

  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/server/
    command: ["/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND"]
    when:
      matrix:
        NEED_SERVER: true

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/fed-server/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D" , "FOREGROUND" ]
    when:
      matrix:
        USE_FEDERATED_SERVER: true

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    pull: true
    when:
      matrix:
        TEST_SUITE: web-acceptance

matrix:
  include:
    # owncloud-coding-standard
    - PHP_VERSION: 7.0
      TEST_SUITE: owncloud-coding-standard

    # Unit Tests
    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: sqlite
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.0
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: javascript
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_INSTALL_APP: true

    # acceptance tests

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityComments
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityCreateUpdate
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityDeleteRestore
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivitySharingExternal
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivitySharingInternal
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityTags
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiActivity
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    # Acceptance tests against latest stable release tarball.
    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityComments
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityCreateUpdate
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityDeleteRestore
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivitySharingExternal
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivitySharingInternal
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_FEDERATED_SERVER: true
      FEDERATION_OC_VERSION: daily-master-qa
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: web-acceptance
      BEHAT_SUITE: webUIActivityTags
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_RELEASE_TARBALL: true

    - PHP_VERSION: 7.1
      OC_VERSION: 10.2.1
      TEST_SUITE: api-acceptance
      BEHAT_SUITE: apiActivity
      DB_TYPE: mysql
      DB_NAME: owncloud
      NEED_CORE: true
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      USE_RELEASE_TARBALL: true
